/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResourceUserJSON } from './resourceUserJSON';
export interface ConsumerJSON {
    createdByUserId: string;
    appType: string;
    description: string;
    createdByUser: ResourceUserJSON;
    enabled: boolean;
    redirectUrl: string;
    developerEmail: string;
    consumerId: number;
    appName: string;
    created: string;
}
