/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountJSON } from './accountJSON';
import { PinResetJSON } from './pinResetJSON';
import { ReplacementJSON } from './replacementJSON';


export interface PhysicalCardJSON {
    allows: Array<string>;

    expiresDate: string;

    networks: Array<string>;

    issueNumber: string;

    replacement: ReplacementJSON;

    enabled: boolean;

    collected: string;

    technology: string;

    cancelled: boolean;

    pinReset: Array<PinResetJSON>;

    serialNumber: string;

    account: AccountJSON;

    validFromDate: string;

    bankCardNumber: string;

    nameOnCard: string;

    posted: string;

    onHotList: boolean;

}
