/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AmountOfMoneyJsonV121 } from './amountOfMoneyJsonV121';
import { CustomerCreditRatingJSON } from './customerCreditRatingJSON';
import { CustomerFaceImageJson } from './customerFaceImageJson';


export interface PostCustomerJsonV210 {
    email: string;

    mobilePhoneNumber: string;

    customerNumber: string;

    highestEducationAttained: string;

    userId: string;

    dobOfDependants: Array<string>;

    dateOfBirth: string;

    creditRating: CustomerCreditRatingJSON;

    lastOkDate: string;

    employmentStatus: string;

    legalName: string;

    creditLimit: AmountOfMoneyJsonV121;

    faceImage: CustomerFaceImageJson;

    dependants: number;

    relationshipStatus: string;

    kycStatus: boolean;

}
