/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ImplementedByJson } from './implementedByJson';
import { SuccessMessage } from './successMessage';


export interface ResourceDocJson {
    errorResponseBodies: Array<string>;

    requestVerb: string;

    requestUrl: string;

    description: string;

    tags: Array<string>;

    isCore: boolean;

    successResponseBody: SuccessMessage;

    exampleRequestBody: SuccessMessage;

    isPsd2: boolean;

    operationId: string;

    implementedBy: ImplementedByJson;

    isObwg: boolean;

    summary: string;

}
