/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AmountOfMoney } from './amountOfMoney';
import { BankId } from './bankId';
import { TransactionTypeId } from './transactionTypeId';


export interface TransactionType {
    shortCode: string;

    description: string;

    id: TransactionTypeId;

    charge: AmountOfMoney;

    bankId: BankId;

    summary: string;

}
