/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE Ltd. 2011 - 2016. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v3.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountId } from './accountId';
import { BankId } from './bankId';
import { CounterpartyId } from './counterpartyId';
import { TransactionRequestAccount } from './transactionRequestAccount';
import { TransactionRequestBody } from './transactionRequestBody';
import { TransactionRequestChallenge } from './transactionRequestChallenge';
import { TransactionRequestCharge } from './transactionRequestCharge';
import { TransactionRequestId } from './transactionRequestId';
import { ViewId } from './viewId';


export interface TransactionRequest {
    otherAccountRoutingAddress: string;

    otherAccountRoutingScheme: string;

    body: TransactionRequestBody;

    challenge: TransactionRequestChallenge;

    name: string;

    startDate: string;

    isBeneficiary: boolean;

    otherBankRoutingScheme: string;

    id: TransactionRequestId;

    thisAccountId: AccountId;

    endDate: string;

    status: string;

    chargePolicy: string;

    from: TransactionRequestAccount;

    thisViewId: ViewId;

    details: string;

    charge: TransactionRequestCharge;

    otherBankRoutingAddress: string;

    thisBankId: BankId;

    type: string;

    counterpartyId: CounterpartyId;

    transactionIds: string;

}
