export * from './func121.service';
import { Func_1_2_1Service } from './func121.service';
export * from './func130.service';
import { Func_1_3_0Service } from './func130.service';
export * from './func140.service';
import { Func_1_4_0Service } from './func140.service';
export * from './func200.service';
import { Func_2_0_0Service } from './func200.service';
export * from './func210.service';
import { Func_2_1_0Service } from './func210.service';
export * from './func220.service';
import { Func_2_2_0Service } from './func220.service';
export * from './func300.service';
import { Func_3_0_0Service } from './func300.service';
export declare const APIS: (typeof Func_1_2_1Service | typeof Func_1_3_0Service | typeof Func_1_4_0Service | typeof Func_2_0_0Service | typeof Func_2_1_0Service | typeof Func_2_2_0Service | typeof Func_3_0_0Service)[];
